version: '3.8'

services:
  wasolgo:
    image: meuconsig/wasolconsumer:1.0.0
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - backend

networks:
  backend:
    external: true
    name: shared_backend